from enum import Enum


class WebHookEvents(str, Enum):
    CHARGE_CREATED = "OPENPIX:CHARGE_CREATED"
    CHARGE_COMPLETED = "OPENPIX:CHARGE_COMPLETED"
    CHARGE_EXPIRED = "OPENPIX:CHARGE_EXPIRED"
    TRANSACTION_RECEIVED = "OPENPIX:TRANSACTION_RECEIVED"
    TRANSACTION_REFUND_RECEIVED = "OPENPIX:TRANSACTION_REFUND_RECEIVED"
    MOVEMENT_CONFIRMED = "OPENPIX:MOVEMENT_CONFIRMED"
    MOVEMENT_FAILED = "OPENPIX:MOVEMENT_FAILED"
    MOVEMENT_REMOVED = "OPENPIX:MOVEMENT_REMOVED"
